// One recommendation generated by the model. Because there is no curated
// dataset, the model supplies the program facts inline. These facts are
// AI-generated and may be inaccurate — always verify on the official page.
export interface Recommendation {
  name: string; // program name, e.g. "MSc Artificial Intelligence"
  university: string;
  country: string;
  city: string;
  field: string; // e.g. "Computer Science", "Robotics", "Data Science"
  durationMonths: number | null;
  tuitionNote: string; // free text — tuition varies by nationality/year; not a single number
  whyItFits: string; // one sentence, references the student's actual profile
  label: "reach" | "match" | "safety";
  rank: number; // 1 = best
}

// What the client form sends alongside the background.
export interface FormValues {
  levelSought: "bachelor" | "master";
  countriesOpenTo: string; // comma-separated in the UI; parsed server-side
  fieldsOfInterest: string; // comma-separated
  maxTuitionEurPerYear: string; // empty = no limit
  interestsFreeText: string;
  otherConstraints: string;
}
